sensor:
  - platform: template
    sensors:
      ### Gas meter template from counter
      gas_meter:
        friendly_name: Gas Meter
        ##value_template: "{{ states('counter.gas_counter') | float * 0.1 }}"
        value_template: "{{ states('counter.gas_counter') | float * 0.1 * 0.9627 * 9.845 }}"
        ##unit_of_measurement: "m³"
        unit_of_measurement: "kWh"
        icon_template: mdi:fire
        device_class: energy
        attribute_templates:
          state_class: total_increasing
          device_class: energy