esphome:
  name: gas-wasser-zaehler
  friendly_name: Gas-Wasser-Zähler

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***********************="

ota:
  password: "*******************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gas-Wasser-Zaehler"
    password: "**************"

captive_portal:

globals:
  - id: total_pulses
    type: int
    restore_value: true
    #initial_value: '292628'  # hier kann der Gaszählerstand initialisiert werden

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO05
      mode: INPUT_PULLUP
    name: "Gas Counter"
    id: esp_gas_sensor
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: id(total_pulses) += 1;

sensor:
  - platform: template
    name: "Gasverbrauch"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:fire"
    accuracy_decimals: 2
    lambda: |-
      return id(total_pulses) * 0.1;